### ISSUE TITLE
rescripts-cli can't find webpack config

### ISSUE THREAD

**Issue by nikitapavets** [rescripts/rescripts#10]
Hi, I was faced the issue, when I set `env` in `package.json`

```
"rescripts": [
  "env"
]
```

```
Error: Cannot find module '/home/.../node_modules/react-scripts/config/webpack.config'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)
    at module.exports (/home/.../node_modules/@rescripts/cli/patch.js:26:30)
    at args (/home/.../node_modules/@rescripts/cli/scripts/start.js:14:17)
    at forEach (/home/.../node_modules/ramda/src/forEach.js:45:5)
    at /home/.../node_modules/ramda/src/internal/_checkForMethod.js:22:72
    at f2 (/home/.../node_modules/ramda/src/internal/_curry2.js:29:14)
    at Object.<anonymous> (/home.../node_modules/@rescripts/cli/scripts/start.js:14:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```
Probably I have that result because a `react-scripts` folder doesn't contain `webpack.config`, but there are `webpack.config.dev` and `webpack.config.prod`.

![image](https://user-images.githubusercontent.com/14897528/50539872-b02a2f80-0b98-11e9-9369-131353017de4.png)

Thanks,

p.s `"react-scripts": "2.1.1"` and `"@rescripts/cli": "^0.0.7"`

**Comment by harrysolovay** [comment]
Hi @nikitapavets — you’re using an old version of react-scripts. Please update to @^2.1.2 — then it should work :)

**Comment by nikitapavets** [comment]
> Hi @nikitapavets — you’re using an old version of react-scripts. Please update to @^2.1.2 — then it should work :)

Hi @harrysolovay, it helped me out, thanks!
