### ISSUE TITLE
Object config runs with an error

### ISSUE THREAD

**Issue by elv1n** [rescripts/rescripts#2]
I'm trying to run rescript with an object in a child file (or directly in parent file)

```
module.exports = {
  webpack: config => config,
  devServer: config => config,
  jest: config => config
}
```
and in parent
```
module.exports = [require.resolve('path/to/child-rescript')]
```
Runs with an error
```
TypeError: Cannot convert undefined or null to object
at hasOwnProperty (<anonymous>)
  at _has (/Users/my-project/node_modules/ramda/src/internal/_has.js:2:42)
  at hasPath (/Users/my-project/node_modules/ramda/src/hasPath.js:35:9)
  at f2 (/Users/my-project/node_modules/ramda/src/internal/_curry2.js:29:14)
  at has (/Users/my-project/node_modules/ramda/src/has.js:32:10)
  at /Users/my-project/node_modules/ramda/src/internal/_curry2.js:22:18
  at f1 (/Users/my-project/node_modules/ramda/src/internal/_curry1.js:18:17)
  at _filter (/Users/my-project/node_modules/ramda/src/internal/_filter.js:7:9)
  at /Users/my-project/node_modules/ramda/src/filter.js:52:3
  at /Users/my-project/node_modules/ramda/src/internal/_dispatchable.js:41:15
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

**Comment by harrysolovay** [comment]
I'm really sorry about that (and thank you for catching this bug). Just [fixed it](https://github.com/rescripts/rescripts/releases/tag/%40rescripts%2Fcli%400.0.6). Please run `npm i @rescript/cli@0.0.6` & it should work :) please let me know if you're still having issues. Otherwise, please close this issue 👍

**Comment by harrysolovay** [comment]
@elv1n just saw your solution & I like it! Enforcing that it be an array so that calling Ramda's `intersperse` doesn't attempt to access undefined methods 💯 let me test this out later tonight & will then merge :)

**Comment by elv1n** [comment]
@harrysolovay Thanks, it works now 👍
sure, I've tested a few cases but not sure in solution
Great library 😉

**Comment by harrysolovay** [comment]
@elv1n thank you! Please let me know if you have any ideas for Rescripts, feature requests, etc :)
